version: '3.8'
services:
  web:
    container_name: web
    build: .
    environment:
      - PORT=8000
    ports:
      - 8000:8000
    depends_on:
      - redis
    command: sh -c "gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    volumes:
      - tempdata:/mosobl/temp

  redis:
    image: "redis:alpine"

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A src.tasks.celery_config:celery_app worker --loglevel=INFO
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - tempdata:/mosobl/temp
    depends_on:
      - redis

  celery_beat:
    container_name: celery_beat
    build: .
    command: celery -A src.tasks.celery_config:celery_app beat --loglevel=INFO
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - tempdata:/mosobl/temp
    depends_on:
      - redis

volumes:
  tempdata:
